[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
#remappings = [
#   "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/src/",
#  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
#]

[invariant]
runs = 128
depth = 128
fail_on_revert = false
